- hosts: dev1 
  become: true
  vars:
    aws_access_key: AKIA4O2MP3QUB4AMRM2A
    aws_secret_key: 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

  tasks:
    - name: installing aws cli
      aws_s3:
        bucket: seerauploads
        object: /etc/passwd
        src: /tmp/sam
        mode: put
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
      delegate_to: "localhost"


    
    - name: downloading aws cli
      aws_s3:
        bucket: seerauploads
        object: /etc/passwd
        dest: /tmp/sam1
        mode: get
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
