- hosts: dev1 
  become: true
  

  tasks:
    - name: installing aws cli
      aws_s3:
        bucket: seerauploads
        object: /etc/passwd
        src: /tmp/sam
        mode: put
        aws_access_key: AKIAQNKZZYLFV25QPOV2
        aws_secret_key: 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
      delegate_to: "localhost"


    
    - name: downloading aws cli
      aws_s3:
        bucket: seerauploads
        object: /etc/passwd
        dest: /tmp/sam1
        mode: get
        aws_access_key: AKIAQNKZZYLFV25QPOV2
        aws_secret_key: 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
